const basicCollection = {
  name: "Basic Cases",
  scrambles: basicScrambles,
  algorithms: basicAlgorithms,
  algorithmSelection: basicAlgorithmSelection,
  caseSelection: basicCaseSelection,
  customAlgorithms: basicCustomAlgorithms,
  trash: basicTrash,
  imgPath: "./images/basic_cases/F2L",
  numberCases: 42,

  divContainer: [],
  caseNumber: [],
  imgContainer: [],
  imgCase: [],
  algorithm: [],
  divAlgorithm: [],
  btnEdit: [],
  imgEdit: [],
  btnDelete: [],
  imgTrash: [],
  trash: [],
  trashElementContainer: [],
  caseNumberTrash: [],
  imgContainerTrash: [],
  imgCaseTrash: [],
  btnRecover: [],
};

const basicBackCollection = {
  name: "Basic Cases Backslot",
  scrambles: basicScramblesBack,
  algorithms: basicAlgorithmsBack,
  algorithmSelection: basicBackAlgorithmSelection,
  caseSelection: basicBackCaseSelection,
  customAlgorithms: basicBackCustomAlgorithms,
  trash: basicTrash,
  imgPath: "./images/basic_cases_back/F2L",
  numberCases: 42,

  divContainer: [],
  caseNumber: [],
  imgContainer: [],
  imgCase: [],
  algorithm: [],
  divAlgorithm: [],
  btnEdit: [],
  imgEdit: [],
  btnDelete: [],
  imgTrash: [],
  trash: [],
  trashElementContainer: [],
  caseNumberTrash: [],
  imgContainerTrash: [],
  imgCaseTrash: [],
  btnRecover: [],
};

const advancedCollection = {
  name: "Advanced Cases",
  scrambles: advancedScrambles,
  algorithms: advancedAlgorithms,
  algorithmSelection: advancedAlgorithmSelection,
  caseSelection: advancedCaseSelection,
  customAlgorithms: advandedCustomAlgorithms,
  trash: advancedTrash,
  imgPath: "./images/advanced_cases/F2L",
  numberCases: 36,

  divContainer: [],
  caseNumber: [],
  imgContainer: [],
  imgCase: [],
  algorithm: [],
  divAlgorithm: [],
  btnEdit: [],
  imgEdit: [],
  btnDelete: [],
  imgTrash: [],
  trash: [],
  trashElementContainer: [],
  caseNumberTrash: [],
  imgContainerTrash: [],
  imgCaseTrash: [],
  btnRecover: [],
};

const groups = [basicCollection, basicBackCollection, advancedCollection];
